[package]
name = "smart_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bevy_egui = "0.24"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
